#!/bin/bash
		git rm    140-1.c
			git rm    140-2
				git rm    140-2.c
					git rm    208
						git rm    208.c
							git rm    226_1
								git rm    226_1.c
									git rm    227_2
										git rm    227_2.c
											git rm    295
												git rm    295.c
													git rm    310
														git rm    310.c
															git rm    330.c
																git rm    350
																	git rm    350.c
																		git rm    358
																			git rm    358.c
																				git rm    365
																					git rm    365.c
																						git rm    67
																							git rm    67.c
																								git rm    67.o
																									git rm    72-2.c
																										git rm    76
																											git rm    76.c
																												git rm    83
																													git rm    83.c
																														git rm    86
																															git rm    86.c
																																git rm    96
																																	git rm    96.c
																																		git rm    96dir
